name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://9bd6ce38a9b0fc97.jomoxc.com:21541/fsa167af8c.a.bdydns.com/1435501072/Firmware/Flyme/meizu18X/9.3.0.0/cn/20220826160621/e0891252/update.zip?r=DEUcID9PXWUKJDE9FAc4BkpcDTk2AFwpAyBsFgoUJxQFQw1%2FChkLJwliLjUKHD9SXGlHaWJGXHpCfWwzDUl4U1YDWGh%2BQ0N8XHtxYUwDeltdAFplfloHOggsNzVNHCMTC0ENPi8RHHsDPSY%2BAAIkUg%3D%3D&xcid=3040fb6c0a804b3b8b8a88ce4749c64f&max_age=7776000&xcsched=3592994678&xclogid=11936714007127222088&xauzkey=mngx_ab6b1bddedf4800ac750a97459a5cabf_1680491557&f_ver=v1&limit_rate=3670016
  ROM_NAME: flyme
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
